services:

  ubuntu:
    container_name: box
    hostname: box
    build: ${BOX}/build
    env_file:
      - ${BOX}/.env
    volumes:
      - ${BOX}/home:/home/me
      - ${BOX}/opt:/opt/box:ro
      - ${DATA}:/data
