services:

  ubuntu:
    container_name: box
    hostname: box
    build: ${BUILD}
    env_file:
      - ${ENV}
    volumes:
      - ./home:/home/me
      - ${SCRIPTS}:/opt/box:ro
      - ${DATA}:/data:ro
