version: '3.8'

services:

  ubuntu:
    container_name: box
    build: build/.
    env_file:
      - .env
    volumes:
      - ./home:/home/ubuntu
      - ./scripts:/opt/box
      - ${DATA}:/data:ro
    ports:
      - 8000:8000